#!/usr/bin/env python3
"""Generate curated everyday spoken English sentences with zh-Hant glosses."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "data" / "sentences.json"
OUT_JS = ROOT / "data" / "sentences.js"

# Hand-curated natural intermediate conversational lines (en, zh)
RAW: dict[str, list[tuple[str, str]]] = {
    "school": [
        ("Excuse me, is this seat taken?", "不好意思，這座位有人坐嗎？"),
        ("Do you mind if I sit here?", "我可以坐這裡嗎？"),
        ("What time does the class start?", "這堂課幾點開始？"),
        ("Sorry I'm late — the bus was delayed.", "抱歉我遲到了，公車誤點了。"),
        ("Could you speak a little slower, please?", "可以請你說慢一點嗎？"),
        ("I didn't catch that. Could you repeat it?", "我沒聽清楚，可以再說一次嗎？"),
        ("What's the homework for today?", "今天的作業是什麼？"),
        ("When is the assignment due?", "作業什麼時候要交？"),
        ("Can I borrow a pen for a second?", "可以借我一支筆一下嗎？"),
        ("Do you have an extra notebook?", "你有多的筆記本嗎？"),
        ("Where is the library from here?", "圖書館從這裡怎麼走？"),
        ("Is the computer lab open after lunch?", "電腦教室午休後有開嗎？"),
        ("I'm looking for Professor Chen's office.", "我在找陳教授的辦公室。"),
        ("Could you help me with this problem?", "可以幫我看一下這題嗎？"),
        ("I don't understand this part.", "這一段我看不懂。"),
        ("Can we study together after class?", "下課後可以一起讀書嗎？"),
        ("Are you free to review for the midterm?", "你有空一起複習期中考嗎？"),
        ("The exam is next Friday, right?", "考試是下週五對吧？"),
        ("How did you do on the quiz?", "你小考考得怎麼樣？"),
        ("I need to talk to my advisor.", "我需要跟指導老師談談。"),
        ("Is there a makeup class this week?", "這週有補課嗎？"),
        ("Which room is Math 101 in?", "數學 101 在哪個教室？"),
        ("The projector isn't working.", "投影機壞了。"),
        ("Could you email me the slides?", "可以把投影片寄給我嗎？"),
        ("I forgot my student ID at home.", "我把學生證忘在家了。"),
        ("Where do I submit the form?", "這份表格要交到哪裡？"),
        ("Is the cafeteria crowded right now?", "現在餐廳很擠嗎？"),
        ("Want to grab lunch between classes?", "想不想趁空堂去吃午餐？"),
        ("I'll meet you by the main gate.", "我在大門口等你。"),
        ("Do we have group presentations today?", "今天有小組報告嗎？"),
        ("Can I join your study group?", "我可以加入你們的讀書會嗎？"),
        ("I need an extension on the paper.", "這篇報告我想申請延期。"),
        ("What's your major?", "你主修什麼？"),
        ("I'm still deciding between two electives.", "我還在兩門選修之間猶豫。"),
        ("Is attendance mandatory for this course?", "這門課一定要出席嗎？"),
        ("The Wi-Fi password isn't working.", "Wi-Fi 密碼連不上。"),
        ("Could you share your notes with me?", "可以跟我分享筆記嗎？"),
        ("I missed yesterday's lecture.", "我昨天缺課了。"),
        ("What did the teacher say about the project?", "老師對專案說了什麼？"),
        ("Let's go over chapter three together.", "我們一起複習第三章吧。"),
        ("Is the registrar's office still open?", "教務處還開著嗎？"),
        ("I need to register for next semester.", "我要辦理下學期註冊。"),
        ("Where can I print my essay?", "哪裡可以印報告？"),
        ("The printer on the second floor is jammed.", "二樓的印表機卡紙了。"),
        ("Do you know when grades will be posted?", "你知道成績什麼時候會公布嗎？"),
        ("I'm a bit nervous about the oral exam.", "我有點緊張口試。"),
        ("Practice your presentation out loud.", "把報告大聲練習幾遍。"),
        ("Don't forget to cite your sources.", "別忘了標註資料來源。"),
        ("Can I leave my bag here for a minute?", "袋子可以放這裡一下嗎？"),
        ("Is anyone sitting next to you?", "你旁邊有人坐嗎？"),
        ("Could you turn up the volume a bit?", "可以請你把音量調大一點嗎？"),
        ("Sorry, I can't hear you from the back.", "抱歉，我在後面聽不太清楚。"),
        ("May I ask a question?", "我可以問個問題嗎？"),
        ("Could you explain that one more time?", "可以再解釋一次嗎？"),
        ("I think there's a typo on the board.", "黑板上好像打錯字了。"),
        ("Which textbook do we need?", "我們需要哪本教科書？"),
        ("Is this book available in the bookstore?", "書店有這本書嗎？"),
        ("I'll send you the reading list.", "我把閱讀清單寄給你。"),
        ("Are we meeting in the classroom or online?", "我們是在教室還是線上見面？"),
        ("The link for the Zoom class is in the email.", "Zoom 上課連結在郵件裡。"),
        ("My microphone isn't working.", "我的麥克風壞了。"),
        ("Can everyone see my screen?", "大家看得到我的螢幕嗎？"),
        ("Please mute yourselves when you're not speaking.", "沒發言時請靜音。"),
        ("I'll upload the recording after class.", "下課後我會上傳錄影。"),
        ("Do we need a lab coat for the experiment?", "實驗需要穿實驗衣嗎？"),
        ("Be careful with the equipment.", "使用器材請小心。"),
        ("Who's presenting first?", "誰先報告？"),
        ("We still need one more teammate.", "我們還缺一個組員。"),
        ("Let's divide the work evenly.", "我們把工作平均分攤吧。"),
        ("I'll take care of the slides.", "投影片我來負責。"),
        ("Can you proofread my draft?", "可以幫我校對草稿嗎？"),
        ("The deadline is midnight tonight.", "截止時間是今晚十二點。"),
        ("I just submitted it a minute ago.", "我一分鐘前剛交出去。"),
        ("Did you get the confirmation email?", "你有收到確認信嗎？"),
        ("The system crashed right before I submitted.", "我要交卷前系統當掉了。"),
        ("Is there a late penalty?", "遲交會扣分嗎？"),
        ("How long is the break between classes?", "兩堂課之間休息多久？"),
        ("Want to get coffee at the campus cafe?", "要不要去校園咖啡廳喝咖啡？"),
        ("I'll catch up with you after the lecture.", "聽完課後我再找你。"),
        ("Have you talked to the TA yet?", "你跟助教談過了嗎？"),
        ("Office hours are on Tuesday afternoons.", "辦公室時段是週二下午。"),
        ("I need a recommendation letter.", "我需要一封推薦信。"),
        ("Could you look over my application?", "可以幫我看一下申請資料嗎？"),
        ("I'm applying for a scholarship.", "我在申請獎學金。"),
        ("When does the semester end?", "這學期什麼時候結束？"),
        ("Are you staying on campus over the break?", "放假期間你會留在校園嗎？"),
        ("Let's celebrate after finals.", "期末考後一起慶祝吧。"),
        ("I can't believe we finished the project.", "真不敢相信專案做完了。"),
        ("Thanks for explaining that so clearly.", "謝謝你解釋得這麼清楚。"),
        ("I really appreciate your help.", "真的很感謝你的幫忙。"),
        ("Sorry for the short notice.", "抱歉臨時才通知。"),
        ("Is it okay if I leave a bit early?", "我可以提早一點離開嗎？"),
        ("I have another class right after this.", "這堂課後我馬上還有另一堂。"),
        ("See you in the next lecture!", "下一堂課見！"),
        ("Good luck on your exam!", "考試加油！"),
        ("You did great on that presentation.", "你報告表現得很棒。"),
        ("Let me know if you need anything.", "有需要再跟我說。"),
        ("I saved you a seat in the front.", "我在前面幫你留了位子。"),
        ("The teacher just called attendance.", "老師剛點完名。"),
        ("Hurry — we're about to start.", "快點，馬上要開始了。"),
    ],
    "office": [
        ("Good morning — how's your day going so far?", "早安，你今天到目前怎麼樣？"),
        ("Do you have a minute to talk?", "你現在方便聊一下嗎？"),
        ("Could we schedule a quick meeting?", "我們可以約個短會嗎？"),
        ("I'll send you the agenda before noon.", "中午前我會把議程寄給你。"),
        ("Is the conference room free at three?", "三點會議室有空嗎？"),
        ("Can we push the call back by fifteen minutes?", "通話可以延後十五分鐘嗎？"),
        ("Sorry, I'm still in another meeting.", "抱歉，我還在另一場會議。"),
        ("I'll join as soon as I can.", "我一有空就加入。"),
        ("Could you share your screen?", "可以分享你的螢幕嗎？"),
        ("I can't hear you clearly — are you muted?", "聽不太清楚，你是不是靜音了？"),
        ("Let's take this offline after the call.", "這件事會後再私下討論。"),
        ("What's the status on that project?", "那個專案進度如何？"),
        ("We're a bit behind schedule.", "我們進度有點落後。"),
        ("I need your feedback by tomorrow.", "我需要你明天前回饋。"),
        ("I'll loop you in on the email thread.", "我會把你加進郵件討論串。"),
        ("Did you see my message on Slack?", "你有看到我在 Slack 的訊息嗎？"),
        ("Please CC me on that reply.", "回覆時請把我 CC 進去。"),
        ("I'll follow up with the client.", "我會再跟客戶追蹤。"),
        ("Could you double-check these numbers?", "可以再幫我核對這些數字嗎？"),
        ("There's a typo in the second paragraph.", "第二段有個錯字。"),
        ("I'll revise the draft and send it over.", "我會修改草稿再寄給你。"),
        ("Who's taking notes for this meeting?", "這次會議誰做筆記？"),
        ("Let's wrap up in five minutes.", "我們五分鐘內結束吧。"),
        ("Any other questions before we go?", "結束前還有其他問題嗎？"),
        ("Thanks everyone for your time.", "謝謝大家抽空參加。"),
        ("I'll send out the meeting notes shortly.", "會議記錄我稍後就寄出。"),
        ("Could you cover for me tomorrow morning?", "明天早上可以幫我代一下嗎？"),
        ("I'm working from home this afternoon.", "今天下午我遠端上班。"),
        ("My laptop is running really slowly.", "筆電跑得好慢。"),
        ("IT said they'll fix it by Friday.", "資訊部說週五前會修好。"),
        ("Where do we keep the spare chargers?", "備用充電器放哪裡？"),
        ("The printer on our floor is out of paper.", "這層的印表機沒紙了。"),
        ("How do I book a visitor badge?", "訪客證要怎麼申請？"),
        ("There's someone waiting for you at reception.", "大廳有人在等你。"),
        ("Can you show our guest to meeting room B?", "可以帶客人去 B 會議室嗎？"),
        ("I'll grab coffee and be right back.", "我去買咖啡馬上回來。"),
        ("Want to get lunch together?", "要不要一起吃午餐？"),
        ("There's a new place near the office.", "公司附近新開了一家店。"),
        ("I'll be out of office next week.", "下週我不在辦公室。"),
        ("Please reach out to Mei while I'm away.", "我不在時請找小美。"),
        ("Could you approve this expense report?", "可以核准這份報銷單嗎？"),
        ("I submitted my timesheet already.", "工時表我已經交了。"),
        ("When is the performance review?", "績效考核是什麼時候？"),
        ("I'd like to discuss my workload.", "我想談談我的工作量。"),
        ("That's a great idea — let's try it.", "好主意，我們試試看。"),
        ("I'm not sure I follow — can you clarify?", "我不太懂，可以再說清楚嗎？"),
        ("Let's align on priorities for this week.", "我們對一下本週優先事項。"),
        ("I'll take the lead on this task.", "這件事我來主導。"),
        ("Feel free to push back if you disagree.", "若不同意歡迎直接說。"),
        ("We need sign-off from legal first.", "要先取得法務核准。"),
        ("The deadline is firm — we can't move it.", "期限是固定的，不能再改。"),
        ("I'll escalate this if we don't hear back.", "若沒回覆我會向上呈報。"),
        ("Can we sync for ten minutes?", "我們可以同步十分鐘嗎？"),
        ("I'll put it on your calendar.", "我會加到你的行事曆。"),
        ("Sorry for the late reply — I was swamped.", "抱歉晚回，我忙翻了。"),
        ("No worries, take your time.", "沒關係，慢慢來。"),
        ("Could you walk me through the process?", "可以帶我走一遍流程嗎？"),
        ("I'm new here — who should I ask about payroll?", "我是新人，薪資該問誰？"),
        ("Welcome aboard! Let me show you around.", "歡迎加入！我帶你逛一下。"),
        ("The kitchen is down the hall on the left.", "茶水間在走廊左邊。"),
        ("Wi-Fi password is on the whiteboard.", "Wi-Fi 密碼在白板上。"),
        ("Don't forget to clock in when you arrive.", "到公司別忘了打卡。"),
        ("Is the all-hands meeting mandatory?", "全體大會一定要參加嗎？"),
        ("I'll present the Q3 numbers.", "第三季數字由我報告。"),
        ("Keep the slides short and clear.", "投影片請保持簡短清楚。"),
        ("Great job on the pitch yesterday.", "昨天提案表現得很棒。"),
        ("The client loved the proposal.", "客戶很喜歡那份提案。"),
        ("We still need to negotiate the budget.", "我們還要談預算。"),
        ("Let's circle back on this tomorrow.", "這件事明天再回頭談。"),
        ("I'll keep you posted.", "有進展我會告訴你。"),
        ("Please don't share this outside the team.", "請勿對外分享。"),
        ("Is this confidential?", "這是機密嗎？"),
        ("I'll lock the document after editing.", "改完我會把文件上鎖。"),
        ("Can you grant me access to the folder?", "可以開那個資料夾權限給我嗎？"),
        ("I accidentally deleted the file.", "我不小心刪掉檔案了。"),
        ("Thankfully we have a backup.", "幸好有備份。"),
        ("My commute was awful this morning.", "今天早上通勤糟透了。"),
        ("Traffic was bumper to bumper.", "車流完全塞死了。"),
        ("I'll stay a bit late to finish this.", "我會多留一下把這做完。"),
        ("Don't burn yourself out.", "別把自己累壞了。"),
        ("Let's take a short break.", "我們休息一下吧。"),
        ("Happy Friday — any plans for the weekend?", "週五快樂，週末有計畫嗎？"),
        ("I'll see you at the offsite next month.", "下個月外訓見。"),
        ("Could you introduce me to the new hire?", "可以介紹我認識新同事嗎？"),
        ("Thanks for covering my shift.", "謝謝你幫我代班。"),
        ("I owe you one.", "我欠你一次。"),
        ("Let's celebrate the launch after work.", "下班後慶祝上線吧。"),
        ("Drinks are on me tonight.", "今晚我請客。"),
        ("I have a conflict at that time.", "那個時間我有撞期。"),
        ("How about Thursday instead?", "改星期四如何？"),
        ("That works for me.", "我可以。"),
        ("I'll confirm with the team and get back to you.", "我跟團隊確認後再回覆你。"),
        ("Please send me the latest version.", "請把最新版本寄給我。"),
        ("I attached the spreadsheet below.", "試算表附在下方。"),
        ("Let me know if anything looks off.", "若有不對的地方跟我說。"),
        ("We're good to go.", "可以開始了。"),
        ("Nice work, everyone.", "大家做得好。"),
        ("Have a good evening!", "晚安，祝你有個好晚上！"),
        ("Talk to you tomorrow.", "明天再聊。"),
        ("Ping me if you need anything.", "有需要就傳訊給我。"),
    ],
    "restaurant": [
        ("Hi, a table for two, please.", "你好，兩位。"),
        ("Do you have a reservation?", "請問有預約嗎？"),
        ("Yes, under the name Fan.", "有，名字是 Fan。"),
        ("We're walking in — is there space?", "我們沒預約，還有位子嗎？"),
        ("How long is the wait?", "大概要等多久？"),
        ("We'd like a booth if possible.", "可以的話想要卡座。"),
        ("Could we sit by the window?", "可以坐窗邊嗎？"),
        ("Is this seat okay?", "這個位子可以嗎？"),
        ("Could we see the menu, please?", "可以看菜單嗎？"),
        ("Do you have an English menu?", "有英文菜單嗎？"),
        ("What's the special today?", "今天的特餐是什麼？"),
        ("What do you recommend?", "你有什麼推薦？"),
        ("Is this dish spicy?", "這道菜辣嗎？"),
        ("Could you make it less spicy?", "可以少辣一點嗎？"),
        ("I'm allergic to peanuts.", "我對花生過敏。"),
        ("Does this contain dairy?", "這有乳製品嗎？"),
        ("Do you have vegetarian options?", "有素食選項嗎？"),
        ("I'll have the grilled salmon.", "我要烤鮭魚。"),
        ("Same for me, please.", "我也一樣。"),
        ("Can we get that to share?", "可以分著吃嗎？"),
        ("I'd like the soup of the day.", "我要今日湯品。"),
        ("Could I get the dressing on the side?", "醬可以另外放嗎？"),
        ("No ice in my water, please.", "水不要加冰，謝謝。"),
        ("I'll have an iced tea.", "我要冰茶。"),
        ("Could we get some more napkins?", "可以多拿幾張餐巾紙嗎？"),
        ("Excuse me — we're ready to order.", "不好意思，我們可以點餐了。"),
        ("Could you give us a few more minutes?", "再給我們幾分鐘好嗎？"),
        ("Is the chicken cooked well-done?", "雞肉可以全熟嗎？"),
        ("I'd like my steak medium rare.", "牛排我想要三分熟。"),
        ("Could you hold the onions?", "洋蔥可以不要嗎？"),
        ("Can I substitute fries for a salad?", "薯條可以換成沙拉嗎？"),
        ("Is there an extra charge for that?", "這樣會加錢嗎？"),
        ("We're celebrating a birthday.", "我們在慶祝生日。"),
        ("Could you bring a candle for the dessert?", "甜點可以附蠟燭嗎？"),
        ("This isn't what I ordered.", "這不是我點的。"),
        ("I ordered the pasta, not the rice.", "我點的是義大利麵，不是飯。"),
        ("Could you heat this up a bit more?", "可以再加熱一點嗎？"),
        ("The food is delicious — thank you.", "料理很好吃，謝謝。"),
        ("Could we get the check, please?", "可以結帳嗎？"),
        ("We're splitting the bill.", "我們要分開付。"),
        ("Can I pay by card?", "可以刷卡嗎？"),
        ("Do you take mobile payments?", "有行動支付嗎？"),
        ("Keep the change.", "不用找了。"),
        ("Could we get this packed to go?", "可以打包嗎？"),
        ("Is takeout available?", "有外帶嗎？"),
        ("How spicy is the curry on a scale of one to five?", "咖哩辣度大概一到五是幾分？"),
        ("I'll try the chef's recommendation.", "我想試試主廚推薦。"),
        ("Could I get a refill on my drink?", "飲料可以續杯嗎？"),
        ("Is refill free?", "續杯免費嗎？"),
        ("The portion is huge!", "份量好大！"),
        ("Could we have some chopsticks?", "可以拿雙筷子嗎？"),
        ("Do you have high chairs for kids?", "有兒童椅嗎？"),
        ("Where is the restroom?", "洗手間在哪裡？"),
        ("Could you turn the AC down a little?", "冷氣可以調弱一點嗎？"),
        ("It's a bit loud in here.", "這裡有點吵。"),
        ("Thanks for seating us so quickly.", "謝謝這麼快安排座位。"),
        ("We'll take the set meal for two.", "我們要雙人套餐。"),
        ("Does the set include dessert?", "套餐有含甜點嗎？"),
        ("I'd like to add a side of vegetables.", "我想加一份蔬菜配菜。"),
        ("Is the soup included with the entree?", "主菜有附湯嗎？"),
        ("Could you bring the appetizers first?", "可以先上開胃菜嗎？"),
        ("We're in a bit of a hurry.", "我們有點趕時間。"),
        ("No rush — we're enjoying the meal.", "不急，我們慢慢吃。"),
        ("Could I taste the wine before ordering a bottle?", "點整瓶前可以先試喝嗎？"),
        ("Just water for now, thanks.", "先只要水，謝謝。"),
        ("I'll skip dessert tonight.", "今晚我不吃甜點了。"),
        ("Could we see the dessert menu?", "可以看甜點菜單嗎？"),
        ("One scoop of vanilla, please.", "香草冰淇淋一球，謝謝。"),
        ("Is service charge included?", "有含服務費嗎？"),
        ("Could you check if our order is coming?", "可以幫忙看看餐好了沒？"),
        ("We've been waiting about twenty minutes.", "我們大概等了二十分鐘。"),
        ("Sorry for the delay — your food is on the way.", "抱歉讓您久等，餐點馬上上來。"),
        ("This soup is a little too salty for me.", "這湯對我來說有點鹹。"),
        ("Could I get another plate?", "可以再拿一個盤子嗎？"),
        ("We're sharing several dishes.", "我們要分食好幾道菜。"),
        ("Please bring empty plates for everyone.", "請幫每位準備空盤。"),
        ("Is outdoor seating available?", "有戶外座位嗎？"),
        ("It's raining — we'd prefer inside.", "在下雨，我們想坐室內。"),
        ("Could you move us to a quieter table?", "可以幫我們換到安靜一點的位子嗎？"),
        ("Happy anniversary!", "週年快樂！"),
        ("Could you take a photo of us?", "可以幫我們拍張照嗎？"),
        ("The lighting is perfect here.", "這裡燈光真好。"),
        ("I'll have whatever she's having.", "她點什麼我就點什麼。"),
        ("Make it two of those.", "再來一份一樣的。"),
        ("Is the kitchen still open?", "廚房還開著嗎？"),
        ("What time do you close?", "你們幾點打烊？"),
        ("Thanks — everything was wonderful.", "謝謝，一切都很棒。"),
        ("We'll definitely come back.", "我們一定會再來。"),
        ("Could I get a receipt, please?", "可以給我收據嗎？"),
        ("Put it on one check.", "算在同一張帳單。"),
        ("I left my jacket on the chair.", "外套忘在椅子上了。"),
        ("Has anyone turned in a black wallet?", "有人撿到黑色皮夾嗎？"),
        ("Please follow me this way.", "請跟我這邊走。"),
        ("Enjoy your meal!", "請慢用！"),
        ("Is everything tasting alright?", "味道還可以嗎？"),
        ("Yes, thank you — it's great.", "很好，謝謝，很棒。"),
        ("Could we get some hot tea?", "可以來壺熱茶嗎？"),
        ("I'll take the leftover soup home.", "剩下的湯我想打包回家。"),
        ("Do you have gluten-free bread?", "有無麩質麵包嗎？"),
        ("Could we get some extra sauce on the side?", "可以多一點醬另外放嗎？"),
    ],
    "station": [
        ("Excuse me, which platform for the train to Taipei?", "不好意思，去台北的火車是幾號月台？"),
        ("Does this train stop at Banqiao?", "這班車有停板橋嗎？"),
        ("Is this the right platform for the express?", "這是對號的月台嗎？"),
        ("What time is the next train?", "下一班車幾點？"),
        ("How often do the trains run?", "火車大概幾分鐘一班？"),
        ("Is there a delay on this line?", "這條線有誤點嗎？"),
        ("The train is running about ten minutes late.", "火車大約晚十分鐘。"),
        ("Where can I buy a ticket?", "哪裡可以買票？"),
        ("Is there a ticket machine nearby?", "附近有售票機嗎？"),
        ("One adult ticket to Kaohsiung, please.", "一張到高雄的成人票，謝謝。"),
        ("A round-trip ticket, please.", "來回票，謝謝。"),
        ("Do you have student discount tickets?", "有學生優惠票嗎？"),
        ("Can I use my EasyCard on this train?", "這班車可以用悠遊卡嗎？"),
        ("Where do I tap in?", "要在哪裡感應進站？"),
        ("My card has no balance left.", "我的卡沒餘額了。"),
        ("Where can I top up my card?", "哪裡可以加值？"),
        ("Is this seat reserved?", "這個位子是劃位的嗎？"),
        ("I think you're in my seat.", "你好像坐到我的位子了。"),
        ("Could you help me find car number five?", "可以幫我找五號車廂嗎？"),
        ("Which way is the exit?", "出口往哪邊？"),
        ("Is there an elevator to the platform?", "月台有電梯嗎？"),
        ("Where are the restrooms?", "洗手間在哪裡？"),
        ("Is there a luggage locker here?", "這裡有寄物櫃嗎？"),
        ("How long does it take to get downtown?", "到市中心大概要多久？"),
        ("Should I transfer at the next station?", "下一站要換車嗎？"),
        ("Which line should I take to the airport?", "去機場要搭哪一條線？"),
        ("Does this bus go to the train station?", "這班公車有到火車站嗎？"),
        ("Where do I catch the shuttle?", "接駁車在哪裡搭？"),
        ("Is the last train already gone?", "末班車已經走了嗎？"),
        ("What time is the last train tonight?", "今晚末班車幾點？"),
        ("Please stand behind the yellow line.", "請站在黃線後面。"),
        ("Mind the gap when you get off.", "下車時小心月台縫隙。"),
        ("Please let passengers off first.", "請先讓下車旅客先下。"),
        ("Is this train crowded?", "這班車很擠嗎？"),
        ("There's more space in the next car.", "下一節車廂比較空。"),
        ("Could you move your bag off the seat?", "可以請你把包包從座位上拿開嗎？"),
        ("Is Wi-Fi available on board?", "車上有 Wi-Fi 嗎？"),
        ("Where can I charge my phone?", "哪裡可以幫手機充電？"),
        ("I missed my stop — what should I do?", "我搭過站了，該怎麼辦？"),
        ("Get off at the next station and go back one stop.", "下一站下車再往回搭一站。"),
        ("Is there a lost and found office?", "有失物招領處嗎？"),
        ("I left my umbrella on the train.", "我把雨傘忘在車上了。"),
        ("Has anyone seen a blue backpack?", "有人看到藍色背包嗎？"),
        ("Where is the information desk?", "詢問處在哪裡？"),
        ("Can you show me on the map?", "可以在地圖上指給我看嗎？"),
        ("I'm looking for the high-speed rail entrance.", "我在找高鐵入口。"),
        ("Do I need to go through security?", "需要安檢嗎？"),
        ("Please have your ticket ready.", "請準備好車票。"),
        ("Boarding begins in five minutes.", "五分鐘後開始上車。"),
        ("This is the final call for train 128.", "128 次列車最後廣播。"),
        ("Please keep the aisle clear.", "請勿堵塞走道。"),
        ("Is priority seating available?", "有博愛座嗎？"),
        ("Would you like my seat? I'm getting off soon.", "要坐我的位子嗎？我快下車了。"),
        ("How many stops until Taipei Main Station?", "到台北車站還有幾站？"),
        ("The doors open on the left.", "左側車門開啟。"),
        ("Please hold on — the train is starting.", "請抓好，列車即將開動。"),
        ("Is there a bathroom on this train?", "這班車有洗手間嗎？"),
        ("The dining car is two cars ahead.", "餐車在前面兩節。"),
        ("Do you sell bottled water here?", "這裡有賣瓶裝水嗎？"),
        ("Is smoking allowed on the platform?", "月台可以吸菸嗎？"),
        ("No, smoking is prohibited throughout the station.", "不行，全站禁菸。"),
        ("Where can I buy a bento?", "哪裡可以買便當？"),
        ("Is there a convenience store upstairs?", "樓上有便利商店嗎？"),
        ("How do I get to the taxi stand?", "計程車招呼站怎麼走？"),
        ("Is the bus stop outside exit three?", "公車站在三號出口外面嗎？"),
        ("I'll meet you at the north exit.", "我在北出口等你。"),
        ("I'm running late — wait for me by the gate.", "我遲到了，在剪票口等我。"),
        ("Did the 3:40 train leave already?", "三點四十分那班已經開了嗎？"),
        ("There's another one in twelve minutes.", "十二分鐘後還有一班。"),
        ("Is reserved seating required?", "一定要劃位嗎？"),
        ("Non-reserved cars are near the front.", "自由座車廂在前面。"),
        ("Can I change my ticket to an earlier train?", "可以把票改成更早的車嗎？"),
        ("Is there a fee to change the ticket?", "改票要手續費嗎？"),
        ("I'd like a refund, please.", "我想退票。"),
        ("Please keep your ticket until you exit.", "出站前請保留車票。"),
        ("The gate won't open — can you help?", "閘門打不開，可以幫忙嗎？"),
        ("Try tapping your card again.", "請再感應一次卡片。"),
        ("Your ticket has already been used.", "這張票已經使用過了。"),
        ("Is this the transfer corridor?", "這是轉乘通道嗎？"),
        ("Follow the signs for the blue line.", "跟著藍線指標走。"),
        ("How far is it to walk to exit A?", "走到 A 出口遠嗎？"),
        ("There's an escalator on your right.", "右手邊有手扶梯。"),
        ("The elevator is out of order.", "電梯故障中。"),
        ("Please use the stairs for now.", "請暫時走樓梯。"),
        ("Is the station accessible for strollers?", "這車站方便推嬰兒車嗎？"),
        ("There's a nursing room near exit two.", "二號出口附近有哺集乳室。"),
        ("Where can I buy a city day pass?", "哪裡可以買一日票？"),
        ("Does the pass cover the airport line?", "一日票有含機場線嗎？"),
        ("I'm visiting — which stop is best for the museum?", "我是觀光客，去博物館在哪一站下最好？"),
        ("Get off at NTU Hospital and walk five minutes.", "在台大醫院站下，再走五分鐘。"),
        ("Is rush hour usually this busy?", "尖峰時間平常都這麼擠嗎？"),
        ("Yes — try coming after 9:30.", "對，建議九點半之後再來。"),
        ("Please stand clear of the closing doors.", "車門關閉，請勿靠近。"),
        ("Next stop is Taipei Main Station.", "下一站，台北車站。"),
        ("Transfer here for the high-speed rail.", "本站可轉乘高鐵。"),
        ("Thank you for riding with us.", "感謝您搭乘。"),
        ("Have a safe trip!", "祝你旅途平安！"),
        ("Could you tell me when we reach the airport?", "到機場時可以提醒我嗎？"),
        ("Sure — I'll tap you when we get there.", "好，到了我會拍你一下。"),
        ("Is my suitcase too big for the overhead rack?", "我的行李箱對頭上行李架太大嗎？"),
        ("You can put it behind the last seats.", "可以放在最後排座位後面。"),
    ],
    "shopping": [
        ("Excuse me, do you work here?", "不好意思，請問你是這裡的店員嗎？"),
        ("I'm just looking, thanks.", "我先看看，謝謝。"),
        ("Could you help me find this in a medium?", "可以幫我找中號嗎？"),
        ("Do you have this in blue?", "這個有藍色嗎？"),
        ("Where are the fitting rooms?", "試衣間在哪裡？"),
        ("Can I try this on?", "我可以試穿嗎？"),
        ("Is there a mirror around here?", "附近有鏡子嗎？"),
        ("This feels a bit tight.", "這件有點緊。"),
        ("Do you have a larger size?", "有大一號嗎？"),
        ("I'll take this one.", "我要這件。"),
        ("How much is this?", "這個多少錢？"),
        ("Is this on sale?", "這個有打折嗎？"),
        ("When does the sale end?", "特價什麼時候結束？"),
        ("Are there any discounts today?", "今天有優惠嗎？"),
        ("Can I use this coupon?", "這張優惠券可以用嗎？"),
        ("Do you price-match?", "有價格匹配嗎？"),
        ("Is tax included in the price?", "價格有含稅嗎？"),
        ("Where is the checkout?", "收銀台在哪裡？"),
        ("Cash or card?", "現金還是刷卡？"),
        ("I'll pay by credit card.", "我用信用卡付。"),
        ("Do you take Apple Pay?", "有 Apple Pay 嗎？"),
        ("Could I get a bag, please?", "可以給我一個袋子嗎？"),
        ("I don't need a bag — I brought my own.", "不用袋子，我有自備。"),
        ("Could you gift-wrap this?", "可以幫我包裝成禮物嗎？"),
        ("Is gift wrapping free?", "禮物包裝免費嗎？"),
        ("I'd like a receipt, please.", "請給我收據。"),
        ("What's your return policy?", "退換貨規定是什麼？"),
        ("Can I return this within fourteen days?", "十四天內可以退貨嗎？"),
        ("Do I need the original receipt to exchange?", "換貨需要原始收據嗎？"),
        ("This item is defective.", "這件商品有瑕疵。"),
        ("Could I get a refund or exchange?", "可以退款或換貨嗎？"),
        ("Where is the customer service desk?", "客服櫃台在哪裡？"),
        ("Is there a restroom in the mall?", "百貨公司裡有洗手間嗎？"),
        ("Where is the food court?", "美食街在哪裡？"),
        ("Which floor is electronics on?", "電子產品在幾樓？"),
        ("I'm looking for running shoes.", "我在找跑鞋。"),
        ("Do you have these in size eight?", "這雙有八號嗎？"),
        ("Could you measure my feet?", "可以幫我量腳嗎？"),
        ("These are more comfortable.", "這雙比較舒服。"),
        ("I'll wear them out of the store.", "我穿著走出店裡。"),
        ("Do you have a loyalty card?", "有會員卡嗎？"),
        ("Can I sign up for points today?", "今天可以辦積分會員嗎？"),
        ("I forgot my membership card.", "我忘帶會員卡了。"),
        ("Can you look up my account with my phone number?", "可以用手機號碼查會員嗎？"),
        ("Is self-checkout available?", "有自助結帳嗎？"),
        ("The scanner isn't reading this barcode.", "掃不到這個條碼。"),
        ("Could you price-check this for me?", "可以幫我查一下價錢嗎？"),
        ("It's cheaper online — do you match it?", "網路上比較便宜，你們有跟價嗎？"),
        ("Do you ship internationally?", "有國際運送嗎？"),
        ("Can I pick this up in store later?", "可以稍後到店取貨嗎？"),
        ("I ordered online for store pickup.", "我網購選了到店取貨。"),
        ("Here's my order number.", "這是我的訂單編號。"),
        ("Is my order ready?", "我的訂單準備好了嗎？"),
        ("Could you hold this for thirty minutes?", "可以幫我留三十分鐘嗎？"),
        ("I'll be right back — don't put it away yet.", "我馬上回來，先別收起來。"),
        ("Do you have a waiting list for this?", "這個有候補名單嗎？"),
        ("When will you restock this item?", "什麼時候會補貨？"),
        ("Could you check the stockroom?", "可以去倉庫看看嗎？"),
        ("We have one left in the back.", "後面倉庫還有一件。"),
        ("I'll take it if you find it.", "找到的話我要。"),
        ("Is this the latest model?", "這是最新款嗎？"),
        ("What's the difference between these two?", "這兩款差在哪裡？"),
        ("Which one do you recommend?", "你推薦哪一個？"),
        ("Is the warranty included?", "有含保固嗎？"),
        ("How long is the warranty?", "保固多久？"),
        ("Do you sell extended warranties?", "有延長保固可以買嗎？"),
        ("Could you demonstrate how it works?", "可以示範怎麼用嗎？"),
        ("Does it come with batteries?", "有附電池嗎？"),
        ("I need a phone case for this model.", "我需要這款手機的保護殼。"),
        ("Do you have screen protectors?", "有螢幕保護貼嗎？"),
        ("Could you install it for me?", "可以幫我貼上嗎？"),
        ("Where are the grocery carts?", "購物車在哪裡？"),
        ("Is there a basket near the entrance?", "入口附近有籃子嗎？"),
        ("Excuse me, where is aisle seven?", "不好意思，第七走道在哪？"),
        ("I'm looking for laundry detergent.", "我在找洗衣精。"),
        ("Is this organic?", "這是有機的嗎？"),
        ("What's the expiration date on this?", "這個有效期限到什麼時候？"),
        ("Are these eggs free-range?", "這些蛋是放養的嗎？"),
        ("Do you have almond milk?", "有杏仁奶嗎？"),
        ("Is the bakery still open?", "烘焙區還開著嗎？"),
        ("I'd like a fresh loaf of bread.", "我想要一條剛烤好的麵包。"),
        ("Could you slice it for me?", "可以幫我切片嗎？"),
        ("Do you have samples today?", "今天有試吃嗎？"),
        ("That smells amazing!", "味道好香！"),
        ("I'll take half a kilo of those apples.", "那些蘋果我要半公斤。"),
        ("Could you put the heavy items at the bottom?", "重的可以放下面嗎？"),
        ("I brought reusable bags.", "我有帶環保袋。"),
        ("Do you charge for plastic bags?", "塑膠袋要收費嗎？"),
        ("Could I get a rain check on this sale item?", "缺貨特價品可以給我雨票嗎？"),
        ("Is there a rain check policy?", "有缺貨補購規定嗎？"),
        ("The price on the shelf is different.", "架上標價不一樣。"),
        ("Could you honor the lower price?", "可以照較低的價格收嗎？"),
        ("Thanks for your help!", "謝謝你的幫忙！"),
        ("Have a nice day!", "祝你有美好的一天！"),
        ("I'll come back if I need anything else.", "還需要的話我會再來。"),
        ("Where can I park for free?", "哪裡可以免費停車？"),
        ("Do you validate parking tickets?", "有停車折抵嗎？"),
        ("How long is free parking with a purchase?", "消費後免費停車多久？"),
        ("Is the elevator this way?", "電梯是往這邊嗎？"),
        ("Which exit leads to the subway?", "哪個出口可以到捷運？"),
        ("Could you point me to the nearest ATM?", "可以指附近的提款機給我嗎？"),
        ("I'm looking for a birthday gift for my mom.", "我在找給媽媽的生日禮物。"),
    ],
    "home": [
        ("I'm home!", "我回來了！"),
        ("Did you lock the front door?", "大門有鎖嗎？"),
        ("Don't forget to take out the trash.", "別忘了倒垃圾。"),
        ("Whose turn is it to do the dishes?", "這次輪到誰洗碗？"),
        ("I'll vacuum the living room.", "客廳我來吸塵。"),
        ("Could you fold the laundry?", "可以幫我摺衣服嗎？"),
        ("The washing machine is making a weird noise.", "洗衣機發出怪聲音。"),
        ("We're out of detergent.", "洗衣精用完了。"),
        ("I'll run to the store later.", "我稍後去一趟商店。"),
        ("What's for dinner tonight?", "今晚吃什麼？"),
        ("I'm too tired to cook — let's order in.", "我太累不想煮，叫外送吧。"),
        ("What do you feel like eating?", "你想吃什麼？"),
        ("There's leftover pasta in the fridge.", "冰箱有剩的義大利麵。"),
        ("Could you set the table?", "可以擺餐具嗎？"),
        ("Dinner's ready!", "晚餐好了！"),
        ("Can you pass the salt?", "可以把鹽遞給我嗎？"),
        ("I'll do the dishes if you cook.", "你煮飯的話我洗碗。"),
        ("Is the dishwasher full?", "洗碗機滿了嗎？"),
        ("Please rinse the plates first.", "盤子請先沖一下。"),
        ("Who left the lights on upstairs?", "樓上誰沒關燈？"),
        ("Turn off the AC when you leave.", "出門請關冷氣。"),
        ("It's freezing in here — can we turn up the heat?", "好冷，可以把暖氣調高嗎？"),
        ("Open a window — it's stuffy.", "開一下窗，好悶。"),
        ("Where's the remote?", "遙控器在哪？"),
        ("I think it's under the couch cushion.", "好像在沙發墊下面。"),
        ("Want to watch a movie tonight?", "今晚想看電影嗎？"),
        ("I'll make some popcorn.", "我去爆米花。"),
        ("Keep the volume down — the neighbors might complain.", "音量小聲一點，鄰居可能會抱怨。"),
        ("I'm heading to bed early.", "我今晚想早點睡。"),
        ("Good night — sleep well.", "晚安，睡個好覺。"),
        ("Did you set an alarm?", "有設鬧鐘嗎？"),
        ("Wake me up if I oversleep.", "如果我睡過頭請叫醒我。"),
        ("Coffee's brewing — want a cup?", "咖啡在煮了，要一杯嗎？"),
        ("I spilled water on the floor.", "我把水灑到地板了。"),
        ("Where do we keep the mop?", "拖把放哪裡？"),
        ("There's a leak under the sink.", "水槽下面在漏水。"),
        ("We should call a plumber.", "該叫水電工了。"),
        ("The Wi-Fi is down again.", "Wi-Fi 又斷了。"),
        ("Have you tried restarting the router?", "你有試過重開分享器嗎？"),
        ("I'll check the fuse box.", "我去看一下電箱。"),
        ("Did the package arrive yet?", "包裹到了嗎？"),
        ("It's by the door.", "在門口。"),
        ("Could you sign for the delivery?", "可以幫我簽收嗎？"),
        ("I need to water the plants.", "我要澆花了。"),
        ("The balcony is a mess.", "陽台好亂。"),
        ("Let's declutter this weekend.", "這週末來整理一下吧。"),
        ("Where should I put these boxes?", "這些箱子要放哪？"),
        ("There's space in the closet.", "衣櫃裡還有空間。"),
        ("I can't find my keys.", "我找不到鑰匙。"),
        ("Check the bowl by the entrance.", "看看門口那個碗裡。"),
        ("Did you feed the cat?", "貓餵了嗎？"),
        ("The dog needs a walk.", "狗該散步了。"),
        ("I'll take him out after dinner.", "晚餐後我帶他出去。"),
        ("Could you hang up the wet towels?", "可以把濕毛巾掛起來嗎？"),
        ("The bathroom is occupied.", "浴室有人在用。"),
        ("I'll be out in five minutes.", "我五分鐘就好。"),
        ("Don't use up all the hot water.", "別把熱水用光。"),
        ("We're almost out of toilet paper.", "衛生紙快沒了。"),
        ("Add it to the shopping list.", "加到購物清單裡。"),
        ("Is anyone expecting guests tonight?", "今晚有人要邀客人來嗎？"),
        ("My friend might drop by later.", "我朋友可能晚點過來。"),
        ("Make yourself at home.", "別客氣，當自己家。"),
        ("Would you like something to drink?", "要喝點什麼嗎？"),
        ("There's juice in the fridge.", "冰箱有果汁。"),
        ("Shoes off at the door, please.", "進門請脫鞋。"),
        ("Here's a pair of slippers.", "這雙拖鞋給你。"),
        ("Sorry about the clutter.", "抱歉有點亂。"),
        ("I just moved in last month.", "我上個月才搬進來。"),
        ("The neighbors are really quiet.", "鄰居很安靜。"),
        ("Someone's ringing the doorbell.", "有人在按門鈴。"),
        ("Could you get that? My hands are full.", "可以幫我去應門嗎？我手上有東西。"),
        ("It's the landlord — rent is due tomorrow.", "是房東，房租明天到期。"),
        ("I already transferred the rent.", "房租我已經轉帳了。"),
        ("The air filter needs replacing.", "空氣濾網該換了。"),
        ("I'll schedule a cleaning service.", "我會約清潔服務。"),
        ("Let's deep-clean the kitchen.", "廚房來個大掃除吧。"),
        ("The fridge smells weird.", "冰箱味道怪怪的。"),
        ("Throw out anything expired.", "過期的都丟掉。"),
        ("I prepped lunch for tomorrow.", "明天的午餐我先備好了。"),
        ("Don't forget your lunchbox.", "別忘了便當盒。"),
        ("I'll pick up groceries on the way home.", "回家路上我會買菜。"),
        ("Need anything from the convenience store?", "便利商店要我帶什麼嗎？"),
        ("Just milk and eggs, please.", "牛奶跟蛋就好，謝謝。"),
        ("The power just went out.", "剛剛停電了。"),
        ("Do we have any candles or flashlights?", "有蠟燭或手電筒嗎？"),
        ("It's back — that was quick.", "來電了，好快。"),
        ("Please charge your phone overnight.", "手機請整晚充電。"),
        ("I left my charger at the office.", "充電器忘在公司了。"),
        ("You can borrow mine.", "你可以借我的。"),
        ("Let's open the curtains — it's sunny out.", "拉開窗簾吧，外面很晴。"),
        ("I love weekends at home.", "我喜歡在家過週末。"),
        ("Want to bake something together?", "要不要一起做點烘焙？"),
        ("The oven is preheating.", "烤箱在預熱了。"),
        ("Don't touch that — it's hot!", "別碰，很燙！"),
        ("It smells so good in here.", "這裡好香。"),
        ("I'll clean up after we finish.", "做完我來收拾。"),
        ("Thanks for helping around the house.", "謝謝你幫忙做家事。"),
        ("Teamwork makes it faster.", "一起做比較快。"),
        ("I'm going to take a quick nap.", "我要小睡一下。"),
        ("Wake me if anything important comes up.", "有重要的事再叫醒我。"),
        ("Home sweet home.", "金窩銀窩不如自己的狗窩。"),
    ],
    "hospital": [
        ("I'd like to make an appointment, please.", "我想預約看診。"),
        ("Do you take walk-ins?", "有接受現場掛號嗎？"),
        ("I have an appointment at 10:30.", "我預約了十點半。"),
        ("Here's my insurance card and ID.", "這是我的健保卡和身分證。"),
        ("Please fill out this form.", "請填寫這份表格。"),
        ("What's the reason for your visit today?", "今天來看診的原因是什麼？"),
        ("I've had a sore throat for three days.", "喉嚨痛已經三天了。"),
        ("I feel dizzy when I stand up.", "站起來會覺得暈。"),
        ("My fever started last night.", "昨晚開始發燒。"),
        ("The pain is on my right side.", "疼痛在右側。"),
        ("On a scale of one to ten, how bad is the pain?", "痛感一到十，大概幾分？"),
        ("It's about a six.", "大概六分。"),
        ("Are you allergic to any medication?", "你對什麼藥過敏嗎？"),
        ("I'm allergic to penicillin.", "我對盤尼西林過敏。"),
        ("Do you have any chronic conditions?", "有慢性病嗎？"),
        ("I take blood pressure medicine daily.", "我每天吃血壓藥。"),
        ("Please have a seat — the doctor will see you soon.", "請稍坐，醫師很快會看你。"),
        ("How long is the wait?", "大概要等多久？"),
        ("You can wait in the waiting area.", "請在候診區等候。"),
        ("Please come this way.", "請跟我這邊走。"),
        ("The doctor will be with you shortly.", "醫師馬上過來。"),
        ("Please roll up your sleeve.", "請捲起袖子。"),
        ("I'm going to take your blood pressure.", "我要幫你量血壓。"),
        ("Your temperature is a little high.", "你的體溫有點高。"),
        ("We need a blood test.", "需要抽血檢查。"),
        ("Please don't eat anything before the test.", "檢查前請不要進食。"),
        ("When will the results be ready?", "報告什麼時候會好？"),
        ("Results should be back in two days.", "報告大約兩天後出來。"),
        ("We'll call you if anything looks concerning.", "若有異常我們會打電話給你。"),
        ("Please take a deep breath.", "請深呼吸。"),
        ("Does it hurt when I press here?", "我按這裡會痛嗎？"),
        ("Yes — right there.", "會，就是那裡。"),
        ("It might be a mild sprain.", "可能是輕微扭傷。"),
        ("You should rest and ice it.", "要休息並冰敷。"),
        ("I'll prescribe some pain relief.", "我會開一些止痛藥。"),
        ("Take one tablet after meals.", "飯後吃一顆。"),
        ("Don't drive after taking this medicine.", "吃這藥後不要開車。"),
        ("Drink plenty of water.", "多喝水。"),
        ("Come back if it gets worse.", "若惡化請再回來。"),
        ("I'd like a second opinion.", "我想再聽第二個意見。"),
        ("Can I get a sick leave certificate?", "可以開請假證明嗎？"),
        ("How many days of rest do you recommend?", "你建議休息幾天？"),
        ("Where is the pharmacy?", "藥局在哪裡？"),
        ("Please wait for your number to be called.", "請等叫到你的號碼。"),
        ("Here's your prescription.", "這是你的處方箋。"),
        ("Take these twice a day for a week.", "這些一天兩次，吃一週。"),
        ("Are there any side effects I should know about?", "有什麼副作用我該注意嗎？"),
        ("You might feel a bit drowsy.", "可能會有點想睡。"),
        ("Can I take this with food?", "可以跟食物一起吃嗎？"),
        ("Avoid alcohol while on this medication.", "服藥期間避免喝酒。"),
        ("Where is the emergency room?", "急診在哪裡？"),
        ("This is an emergency — please help!", "這是緊急狀況，請幫忙！"),
        ("My friend fainted.", "我朋友昏倒了。"),
        ("Please stay calm — help is on the way.", "請保持冷靜，救援正在來。"),
        ("Is there a wheelchair available?", "有輪椅可以借用嗎？"),
        ("Where is the X-ray department?", "放射線科在哪裡？"),
        ("Please remove any metal objects.", "請取下金屬物品。"),
        ("Lie still during the scan.", "掃描時請保持不動。"),
        ("The MRI will take about thirty minutes.", "磁振造影大約三十分鐘。"),
        ("Are you pregnant?", "你有懷孕嗎？"),
        ("Please change into this gown.", "請換上這件檢查袍。"),
        ("Your personal belongings are in this locker.", "個人物品放在這個置物櫃。"),
        ("How do I get to the lab?", "檢驗室怎麼走？"),
        ("Follow the blue line on the floor.", "跟著地板藍線走。"),
        ("I need to renew my prescription.", "我要續領處方藥。"),
        ("Has my doctor authorized a refill?", "醫生有核准續領嗎？"),
        ("I'd like to schedule a follow-up.", "我想約回診。"),
        ("Does next Tuesday afternoon work?", "下週二下午可以嗎？"),
        ("Could you send the records to my family doctor?", "可以把病歷寄給我的家醫嗎？"),
        ("I need a referral to a specialist.", "我需要轉診到專科。"),
        ("Which department should I go to?", "我該去哪個科別？"),
        ("Please check in at the counter first.", "請先到櫃台報到。"),
        ("Your number is 47.", "你的號碼是 47。"),
        ("They're calling number 45 now.", "現在叫到 45 號。"),
        ("Is parking free for patients?", "病患停車免費嗎？"),
        ("Validate your ticket at the exit.", "離場時請折抵停車單。"),
        ("Where can I get a mask?", "哪裡可以拿口罩？"),
        ("Please sanitize your hands before entering.", "進入前請先消毒雙手。"),
        ("Is visiting allowed today?", "今天可以探病嗎？"),
        ("Visiting hours are from 2 to 8 p.m.", "探病時間是下午兩點到八點。"),
        ("Only two visitors at a time.", "一次限兩位訪客。"),
        ("My relative is in room 312.", "我的親友在 312 病房。"),
        ("How is the patient doing?", "病人狀況如何？"),
        ("Stable for now — we're monitoring closely.", "目前穩定，我們持續觀察。"),
        ("When can they be discharged?", "什麼時候可以出院？"),
        ("Possibly tomorrow if the fever stays down.", "若燒退下來，可能明天。"),
        ("Please bring a caregiver for discharge.", "出院時請帶一位陪同者。"),
        ("I need help understanding the bill.", "帳單我看不太懂，需要說明。"),
        ("Does insurance cover this procedure?", "這個處置有健保給付嗎？"),
        ("There's a co-pay of three hundred dollars.", "部分負擔是三百元。"),
        ("Can I pay by credit card?", "可以刷卡嗎？"),
        ("Please keep this receipt for insurance.", "請保留這張收據給保險用。"),
        ("I'd like a copy of my medical report.", "我想要病歷報告影本。"),
        ("It'll be ready in about an hour.", "大約一小時後可以拿。"),
        ("Thank you for taking care of me.", "謝謝你們照顧我。"),
        ("Feel better soon!", "早日康復！"),
        ("Call us if symptoms return.", "症狀再出現請打電話給我們。"),
        ("Is the pediatric clinic on this floor?", "小兒科在這層嗎？"),
        ("The dental clinic is on the third floor.", "牙科在三樓。"),
        ("I need a flu shot.", "我要打流感疫苗。"),
        ("Do I need an appointment for vaccination?", "打疫苗需要預約嗎？"),
        ("Please wait fifteen minutes after the shot.", "施打後請等候十五分鐘。"),
    ],
}


def dedupe(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for en, zh in pairs:
        key = en.strip().lower()
        if key in seen:
            continue
        seen.add(key)
        out.append((en.strip(), zh.strip()))
    return out


def main() -> None:
    items: list[dict] = []
    nid = 1
    counts: dict[str, int] = {}
    for scene, pairs in RAW.items():
        pairs = dedupe(pairs)
        if len(pairs) < 100:
            raise SystemExit(f"{scene}: only {len(pairs)} unique sentences")
        # Keep first 100 if slightly over
        pairs = pairs[:100] if len(pairs) > 100 else pairs
        # If still under 100 somehow, fail
        if len(pairs) < 100:
            raise SystemExit(f"{scene}: need >=100, got {len(pairs)}")
        for en, zh in pairs:
            items.append({"id": nid, "scene": scene, "en": en, "zh": zh})
            nid += 1
        counts[scene] = len(pairs)

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(items, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    js = "window.VOCAB_SENTENCES = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n"
    OUT_JS.write_text(js, encoding="utf-8")
    print("Wrote", len(items), "sentences")
    print(counts)
    # Basic English sanity: no empty, reasonable length
    for it in items:
        assert it["en"] and it["zh"]
        assert 3 <= len(it["en"]) <= 120, it
        assert it["scene"] in RAW


if __name__ == "__main__":
    main()
